CREATE TYPE "public"."experience_level" AS ENUM('BEGINNER', 'INTERMEDIATE', 'EXPERIENCED', 'EXPERT');--> statement-breakpoint
CREATE TABLE "friluftskompis_trip_group_member" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "friluftskompis_trip_group_member_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"groupId" integer NOT NULL,
	"name" varchar(256) NOT NULL,
	"age" integer,
	"experienceLevel" "experience_level",
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "friluftskompis_trip_group" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "friluftskompis_trip_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"createdById" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "friluftskompis_trip_group_member" ADD CONSTRAINT "friluftskompis_trip_group_member_groupId_friluftskompis_trip_group_id_fk" FOREIGN KEY ("groupId") REFERENCES "public"."friluftskompis_trip_group"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "trip_group_member_group_idx" ON "friluftskompis_trip_group_member" USING btree ("groupId");--> statement-breakpoint
CREATE INDEX "trip_group_created_by_idx" ON "friluftskompis_trip_group" USING btree ("createdById");