CREATE TABLE "friluftskompis_trip_cabin" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "friluftskompis_trip_cabin_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tripId" integer NOT NULL,
	"cabinId" varchar(64) NOT NULL,
	"cabinName" varchar(256) NOT NULL,
	"dayNumber" integer DEFAULT 1 NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "friluftskompis_trip_expense" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "friluftskompis_trip_expense_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tripId" integer NOT NULL,
	"description" varchar(256) NOT NULL,
	"amount" real NOT NULL,
	"paidBy" varchar(256) NOT NULL,
	"splitAmong" json DEFAULT '[]'::json NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "friluftskompis_trip" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "friluftskompis_trip_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"groupId" integer NOT NULL,
	"name" varchar(256) NOT NULL,
	"routeId" varchar(64),
	"routeName" varchar(256),
	"routeLon" real,
	"routeLat" real,
	"startDate" varchar(10),
	"endDate" varchar(10),
	"shareToken" varchar(64),
	"createdById" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "friluftskompis_trip_shareToken_unique" UNIQUE("shareToken")
);
--> statement-breakpoint
ALTER TABLE "friluftskompis_trip_cabin" ADD CONSTRAINT "friluftskompis_trip_cabin_tripId_friluftskompis_trip_id_fk" FOREIGN KEY ("tripId") REFERENCES "public"."friluftskompis_trip"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "friluftskompis_trip_expense" ADD CONSTRAINT "friluftskompis_trip_expense_tripId_friluftskompis_trip_id_fk" FOREIGN KEY ("tripId") REFERENCES "public"."friluftskompis_trip"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "friluftskompis_trip" ADD CONSTRAINT "friluftskompis_trip_groupId_friluftskompis_trip_group_id_fk" FOREIGN KEY ("groupId") REFERENCES "public"."friluftskompis_trip_group"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "trip_cabin_trip_idx" ON "friluftskompis_trip_cabin" USING btree ("tripId");--> statement-breakpoint
CREATE INDEX "trip_expense_trip_idx" ON "friluftskompis_trip_expense" USING btree ("tripId");--> statement-breakpoint
CREATE INDEX "trip_group_idx" ON "friluftskompis_trip" USING btree ("groupId");--> statement-breakpoint
CREATE INDEX "trip_share_token_idx" ON "friluftskompis_trip" USING btree ("shareToken");--> statement-breakpoint
CREATE INDEX "trip_created_by_idx" ON "friluftskompis_trip" USING btree ("createdById");